const artifactReflections = {
  "safeclick-ai": [
    "Creating SafeClick AI helped me understand that a useful generative AI solution should begin with a clearly defined user problem rather than the technology itself. I practiced writing focused instructions, protecting private information, communicating uncertainty, and testing the assistant with realistic phishing situations. This process showed me that responsible design requires attention to how users may react when they feel afraid or pressured.",
    "My strongest contribution was combining my cybersecurity experience with calm language and practical actions that a nontechnical user could follow. The scenario testing also taught me to evaluate more than whether the assistant produced an answer. I had to consider safety, accuracy, privacy, clarity, refusal behavior, and whether the response directed the user toward an appropriate human or official source.",
    "In future work, I would test the assistant with a larger and more diverse group of users and use a formal scoring rubric for every scenario. I would also strengthen escalation guidance and periodically review the instructions as phishing methods change. This artifact demonstrates my growth in prompt design, human-centered problem solving, cybersecurity communication, and responsible AI boundaries."
  ],
  "ml-vs-deep-learning": [
    "This comparison strengthened my understanding that machine learning and deep learning should be selected according to the problem, the available data, and the consequences of the decision. Credit-risk prediction illustrated why traditional machine learning can be valuable when the data are structured and decision-makers need an explanation. Medical-image analysis showed why deep learning is useful when important patterns are difficult to define manually.",
    "The most important lesson was that the most complex method is not automatically the best method. Model selection also requires consideration of data volume, computational resources, explainability, error costs, privacy, and operational context. Preparing this artifact improved my ability to translate technical differences into language that a business leader or client can understand.",
    "If I expanded this work, I would build a controlled benchmark comparing multiple algorithms on the same dataset. I would report predictive performance, training time, calibration, interpretability, and the effect of different decision thresholds. This would add measured evidence to the research and help me make a more complete recommendation for a specific organization."
  ],
  "adaptive-neural-network": [
    "The adaptive neural-network experiment helped me see that model performance is connected to the environment in which the model operates. The model achieved 94.4% accuracy in its original setting, dropped to 81.7% when the data pattern changed, and reached 95.0% after retraining. This made concept drift easier for me to understand because the consequences were visible and measurable.",
    "I also connected the technical result to adaptive leadership. A leader cannot assume that a method will remain effective simply because it worked in the past. Monitoring, feedback, communication, and willingness to adjust are necessary when conditions change. At the same time, adaptation should preserve the mission, ethical standards, and accountability rather than becoming an excuse for uncontrolled change.",
    "In a future version, I would repeat the experiment across multiple random samples, calculate confidence intervals, compare several drift-detection methods, and define thresholds for review or retraining. I would also evaluate whether adaptation changes performance differently across important groups. This artifact demonstrates my development in Python, neural networks, model monitoring, visualization, and change leadership."
  ],
  "responsible-data-pipeline": [
    "Workshop Four changed the way I think about machine-learning problems because I learned that many failures begin with the data rather than the algorithm. Using the real Wisconsin Diagnostic Breast Cancer dataset made the lesson more meaningful. I created controlled training-data defects and produced evidence showing 37 missing values, eight duplicates, and 34 values outside the learned limits before cleaning, with all three issues addressed afterward.",
    "The model results also taught me the importance of reporting evidence honestly. Cleaning did not create a dramatic increase in accuracy, although ROC-AUC improved slightly from 0.9958 to 0.9962. Instead of exaggerating the improvement, I explained that the pipeline and separable dataset reduced the effect of the controlled defects. I also documented that the dataset lacks demographic attributes, so demographic fairness cannot be evaluated from this evidence.",
    "I will apply this learning by including data-quality checks, provenance, leakage prevention, privacy review, and limitation statements at the beginning of future AI projects. A stronger extension would involve external data, stakeholder-defined quality thresholds, and evaluation across relevant populations. This artifact shows my ability to connect real-data preparation with ethical judgment, transparent communication, and responsible change leadership."
  ],
  "model-validation-verification": [
    "Workshop Five helped me understand validation and verification as separate but connected responsibilities. Verification confirmed that the 30-feature schema, target values, missingness checks, record counts, and train-validation-test separation were implemented correctly. Validation then examined whether the candidate models performed well on data that were not used for training.",
    "The difference between validation and test performance was especially valuable. Random forest detected every malignant case in the validation split, but the untouched test set produced 97.67% malignant recall, 91.23% accuracy, and one false negative. This result showed why leaders should not present the best development score as expected real-world performance. Integrity requires reporting errors, uncertainty, and the limits of the available evidence.",
    "I will apply this lifecycle approach by defining metrics, verification checks, data splits, threshold rules, release authority, monitoring owners, and escalation procedures before deployment. I would strengthen this artifact through external clinical validation, calibration analysis, subgroup evaluation, and drift monitoring. The project demonstrates my growth in model selection, threshold evaluation, verification, final testing, ethical release judgment, and iterative learning."
  ]
};
